# makefile for Program #5 CMP101  NOAH SPURRIER

#brainmaze : main.o maze.o
brainmaze : main.o
	gcc main.o -lm -o brainmaze
#	gcc main.o maze.o -lm -o brainmaze

#main.o : main.c maze.h
main.o : main.c
	gcc -g -c -ansi -pedantic -Wall main.c

#maze.o : maze.c maze.h
#maze.o : maze.c
#	gcc -g -c -ansi -pedantic -Wall maze.c

